###    Docker Compose for run UltraVNC repeater container

uncrepeater:
  image: grigiu/vncrepeater:latest
  privileged: true

  restart: unless-stopped

  ports:
  - "5500:5500"
  - "5901:5901"
  
  tty: true

  environment:
    - TERM=xterm                                
